services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: POS
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Backend Service (Node.js)
  backend:
    build:
      context: . # Backend is in the root folder
      dockerfile: Dockerfile # Use the backend Dockerfile
    container_name: node_backend
    environment:
      MYSQL_ROOT_PASSWORD: 12345678 # Root user password
      MYSQL_DATABASE: POS # Create this database
    ports:
      - "5030:5030"
    depends_on:
      mysql:
        condition: service_healthy # Wait for MySQL to be healthy
    networks:
      - app-network

  # Frontend Service (React.js)
  frontend:
    build:
      context: ./client # Frontend is in the "client" folder
      dockerfile: Dockerfile # Use the frontend Dockerfile
    container_name: react_frontend
    environment:
      REACT_APP_API_URL: http://localhost:5030 # Point frontend to backend API
    ports:
      - "5373:5373"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
